device:
    qubit:
        T1: [70, 120, 40, 5] # [us]
        f_ge: [743.119, 3476.716, 166.5217, 456.7] # [MHz]
        f_ef: [649.12, 3376.34, -59.294, 295.9599] # [MHz]
        f_EgGf: [2013, -1, 2682, 2385.8] # [MHz] expect to be ge_1 + ef_1 - ge_0
        gs: [43, 0, 54, 40] # [MHz] from theoretical comparison for ZZ shift
        pulses:
            pi_ge:
                gain: [27145, 15419, 13869, 7000]
                sigma: [0.035, 0.025, 0.020, 0.025] # [us]
                type: gauss
            pi_ef:
                gain: [3006, 10922, 14543, 4728]
                sigma: [0.035, 0.025, 0.025, 0.025] # [us]
                type: gauss
            pi_EgGf:
                gain: [1000, 0, 7800, 10000]
                sigma: [0.100, 0, 0.170, 0.253] # [us]
                type: const
    
    readout:
        trig_offset: 120 # [Clock ticks]
        # frequency: [810.409984606071, -804.7555447534925, -82.3, 79.3372763161615] # [MHz] max: 860 MHz, must be in separate bins = fs/16 (hi/lo power: 7.681/7.686, 5.775/5.781, 6.787/6.793, 6.949/6.955)
        frequency: [810.409984606071, -804.25, -82.3, 79.3372763161615] # [MHz] max: 860 MHz, must be in separate bins = fs/16 (hi/lo power: 7.681/7.686, 5.775/5.781, 6.787/6.793, 6.949/6.955)
        lo_sideband: [1, -1, 1, 1] # whether taking the +/- sideband after LO
        gain: [0.085, 0.07, 0.04, 0.07] # [MUX units: range -1 to 1, signed amplitude]
        # phase: [0, 0, 90, 0] # degrees 
        # threshold_ge: [0, -73, 0.75, 0] # adc units
        # threshold_ef: [1, 1, 1, 1] # adc units
        readout_length: [10, 10, 10, 10] # [us]
        relax_delay: [200, 300, 150, 50] # [us]
    
hw:
    lo:
        readout:
            frequency: 5925e6
            power: 10 # mixer wants 7 dBm
    soc:
        dacs:
        # dac types: full (full gen - all gens in standard firmware) or int4, mux4 (q3diamond)
        # For mux4, all 4 readouts are on the same DAC (ch 6). Need to make sure none of the
        # 4 muxed readout freqs are not in the same bin, which are fs/16 wide
            qubit:
                ch: [0, 5, 0, 0]
                # ch: [0, 4, 0, 0]
                type: ['int4', 'full', 'int4', 'int4']
                mixer_freq: [4000, 0, 4000, 4000]
                nyquist: [2, 2, 2, 2]
            swap:
                ch: [4, -1, 4, 4]
                type: ['full', None, 'full', 'full']
                # nyquist: [2, 0, 2, 2]
                nyquist: [1, 0, 1, 1]
            readout:
                # ch: 1
                # type: 'full'
                # nyquist: 1
                # ch: 0
                # type: 'int4'
                # mixer_freq: 2000 # [MHz] freq to mix up
                # nyquist: 1
                ch: 6
                type: 'mux4'
                mixer_freq: 950 # [MHz] freq to mix up
                nyquist: 1
        adcs:
            readout:
                ch: [0, 1, 2, 3]
            
aliases: # for use in instrument manager
    readout_LO: SC_26C1
    soc: Qick187