device:
    qubit:
        T1: [35, 80, 50, 44] # us
        f_ge: [845.00, 3478.17, 168.08, 465.8] # MHz
        f_ef: [658, 3377, -55, 293] # MHz
        f_EgGf: [2000, 0, 2000, 2000] # MHz expect to be ge_1 + ef_1 - ge_0
        pulses:
            pi_ge:
                gain: [10585, 13251, 13657, 12683]
                sigma: [0.035, 0.030, 0.020, 0.015] # [us]
                type: gauss
            pi_ef:
                gain: [1000, 1000, 1000, 1000]
                sigma: [0.100, 0.100, 0.100, 0.100] # [us]
                type: gauss
            pi_EgGf:
                gain: [1000, 0, 1000, 1000]
                sigma: [0.100, 0, 0.100, 0.100] # [us]
                type: gauss
    
    readout:
        trig_offset: 120 # [Clock ticks]
        frequency: [600.9, -665.3, -292.1, -130.4] # [MHz] max: 800 MHz, must be in separate bins = fs/16 (hi/lo power: 7.681/7.686, 5.775/5.781, 6.787/6.793, 6.949/6.955)
        gain: [0.085, 0.03, 0.025, 0.07] # [MUX units: range -1 to 1, signed amplitude]
        phase: [0, 0, 0, 0] # degrees 
        threshold_ge: [0, 0, 0, 0] # adc units
        threshold_ef: [1, 1, 1, 1] # adc units
        readout_length: [5, 5, 5, 5] # [us]
        relax_delay: [100, 250, 150, 150] # [us]
    
hw:
    lo:
        readout:
            frequency: 6.1e9
            power: 10 # mixer wants 7 dBm
    soc:
        dacs:
        # dac types: full (full gen - all gens in standard firmware) or int4, mux4 (q3diamond)
        # For mux4, all 4 readouts are on the same DAC (ch 6). Need to make sure none of the
        # 4 muxed readout freqs are not in the same bin, which are fs/16 wide
            qubit:
                ch: [0, 5, 0, 0]
                type: ['int4', 'full', 'int4', 'int4']
                mixer_freq: [4000, 0, 4000, 4000]
                nyquist: [2, 2, 2, 2]
            swap:
                ch: [4, -1, 4, 4]
                type: ['full', None, 'full', 'full']
                nyquist: [1, 0, 1, 1]
            readout:
                # ch: 1
                # type: 'full'
                # nyquist: 1
                # ch: 0
                # type: 'int4'
                # mixer_freq: 2000 # [MHz] freq to mix up
                # nyquist: 1
                ch: 6
                type: 'mux4'
                mixer_freq: 985 # [MHz] freq to mix up
                # mixer_freq: 850 
                nyquist: 1
        adcs:
            readout:
                ch: [0, 1, 2, 3]
            
aliases: # for use in instrument manager
    readout_LO: SC_26C1
    soc: Qick187