device:
    qubit:
        T1: [97, 62, 46, 58] # [us]
        f_ge: [823.0681204610527, 3470.13, 153.92796237453135, 447.5819924260869] # [MHz]
        f_Q1_ZZ: [3468.889513688846, 3470.20476419, 3465.25270434, 3469.12083078] # [MHz] frequency of Q1 when other qubits are in e
        f_ef: [633.210668158286, 3364.266, -71.90192894145498, 275.76433968698353] # [MHz]
        f_EgGf: [2009.95, 3364.24341488, 2683.62545251, 2389.97142246] # [MHz] expect to be ge_1 + ef_1 - ge_0
        gs: [43, 0, 54, 40] # [MHz] from theoretical comparison for ZZ shift
        pulses:
            pi_ge:
                gain: [22692, 22139, 22539, 28755]
                sigma: [0.0386, 0.0196, 0.0433, 0.0276] # [us]
                type: [gauss, gauss, gauss, gauss]
            pi_ef:
                gain: [12488, 14667, 20765, 29402]
                sigma: [0.025, 0.025, 0.035, 0.015] # [us]
                type: gauss
            pi_Q1_ZZ: # pi pulse length for Q1 when other qubits are in e
                gain: [25000, 0, 25000, 25000]
                # sigma: [0.0348, 0, 0.0160, 0.0175] # [us]
                # sigma: [0.0220, 0, 0.0160, 0.0175] # [us]
                sigma: [0.0174, 0, 0.0160, 0.0175] # [us]
                type: [gauss, gauss, gauss, gauss]
            pi_EgGf:
                gain: [3450, 0, 2750, 2850]
                sigma: [0.2186, 0, 0.232, 0.290] # [us]
                type: const

    
    readout:
        trig_offset: 125 # [Clock ticks]
        # frequency: [810.409984606071, -804.7555447534925, -82.3, 79.3372763161615] # [MHz] max: 860 MHz, must be in separate bins = fs/16 (hi/lo power: 7.681/7.686, 5.775/5.781, 6.787/6.793, 6.949/6.955)
        frequency: [814.069, -808.975, -79.784, 81.64542225717739] # [MHz] max: 860 MHz, must be in separate bins = fs/16 (hi/lo power: 7.681/7.686, 5.775/5.781, 6.787/6.793, 6.949/6.955)
        lo_sideband: [1, -1, 1, 1] # whether taking the +/- sideband after LO
        gain: [0.920, 0.780, 0.270, 0.850] # [MUX units: range -1 to 1, signed amplitude]
        # phase: [0, 0, 90, 0] # degrees 
        # threshold_ge: [0, -73, 0.75, 0] # adc units
        # threshold_ef: [1, 1, 1, 1] # adc units
        readout_length: [10, 10, 10, 10] # [us]
        relax_delay: [291, 158, 140, 173] # [us]
    
hw:
    soc:
        dacs:
        # dac types: full (full gen - all gens in standard firmware) or int4, mux4 (q3diamond)
        # For mux4, all 4 readouts are on the same DAC (ch 6). Need to make sure none of the
        # 4 muxed readout freqs are not in the same bin, which are fs/16 wide
            qubit:
                ch: [0, 5, 0, 0]
                # ch: [0, 4, 0, 0]
                type: ['int4', 'full', 'int4', 'int4']
                mixer_freq: [4000, 0, 4000, 4000]
                nyquist: [2, 2, 2, 2]
            swap:
                ch: [4, -1, 4, 4]
                type: ['full', None, 'full', 'full']
                # nyquist: [2, 0, 2, 2]
                nyquist: [1, 0, 1, 1]
            readout:
                # ch: 1
                # type: 'full'
                # nyquist: 1
                # ch: 0
                # type: 'int4'
                # mixer_freq: 2000 # [MHz] freq to mix up
                # nyquist: 1
                ch: 6
                type: 'mux4'
                mixer_freq: 950 # [MHz] freq to mix up
                nyquist: 1
        adcs:
            readout:
                ch: [0, 1, 2, 3]
    lo:
        readout:
            frequency: 5925e6
            power: 7 # mixer wants 7 dBm
            
aliases: # for use in instrument manager
    readout_LO: SC_26C1
    soc: Qick187