device:

    readout:
        trig_offset: 145 # [Clock ticks]
        lo_sideband: [1, 1, 1, 1] # whether taking the +/- sideband after LO [we no longer have a readout LO]
        frequency: [-390.95193842109995, 5794.90833333, 501.288233333334, -229.94910723] # [MHz] max: 860 MHz, must be in separate bins = fs/16 (hi/lo power: 6.808, 5.794, 7.700, 6.966)
        frequency_ef: [-392.9315036040767, 5794.925333329999, 499.41074988962544, -231.37577390000007]
        gain: [0.25, 0.30, 0.85, 0.35] # [MUX units: range -1 to 1, signed amplitude]
        readout_length: [8.0, 10.0, 7.0, 6.0] # [us]

        readout_length_ef: [8.0, 7.0, 4.0, 4.0] # [us]
        relax_delay: [450, 450, 450, 450] # [us]
    qubit:
        f_ge: [4110.428247950795, 4105.038816552946, 4110.198576889643, 4109.933722963169, 3442.8436398119666, 3448.2234633901926, 3447.122665677232, 3446.8985639748066, 4762.066958508102, 4761.098043820929, 4762.201572322125, 4761.678033261405, 4381.167436176662, 4380.365504198304, 4381.142621732222, 4381.679544300405]
        f_ef: [3884.3737933985267, 0.0, 0.0, 0.0, 0.0, 3347.761789059698, 0.0, 0.0, 4571.9056482340775, 4570.482481434396, 4572.387578885567, 0.0, 4211.706921103304, 4207.262930371132, 0.0, 4209.981140744554]
        f_EgGf: [2686.53594683, 0, 2017.3, 2414.92850999] # [MHz] expect to be ge_1 + ef_1 - ge_0; drive on Q1 to perform a swap with Qx
        # f_EgGf_Q: [0, 0, 5885.4, 5138.925]
        f_EgGf_Q: [0, 0, 5883.96, 5147.14]
        # drive on Qx to perform a swap with Q1. For Q2: set Q0 in g before starting. For Q3: set Q0 in e before startin
        # f_f0g1: [1185.65, 998.45, 1642.2333333333333, 1613.44860993] # [MHz] expect to be ge_1 + ef_1 - ge_0; drive on QX to perform a swap with resX
        f_f0g1: [1184.4, 999.8, 1632.9833333333333, 1620.9166666666665] # [MHz] expect to be ge_1 + ef_1 - ge_0; drive on QX to perform a swap with resX
        gs: [52.40296404695958, 54.81794456602636, 43.49513117058557, 4.930653352423196, 2.6415018214608046, 6.386231497692186] # [MHz] g01, g12, g13, g02, g03, g23 from theoretical comparison for ZZ shift
        # ZZs: [0.0, -5.458240611352267, -0.1043071446219983, -0.5526523031812758, -5.515347366312653, 0.0, -1.2506620530984947, -1.4516829853719173, -0.1043071446219983, -1.1204132499606203, 0.0, -0.48324088539629884, -0.5526523031812758, -1.2926978289897306, -0.5275917408453097, 0.0]


        pulses:
            pi_ge:
                sigma: [0.02, 0.02, 0.02, 0.02, 0.025, 0.025, 0.025, 0.025, 0.015, 0.015, 0.015, 0.015, 0.025, 0.025, 0.025, 0.025] # [us]
                gain: [1854, 1984, 0, 0, 2834, 2631, 3310, 3132, 0, 14379, 14389, 0, 0, 965, 0, 963]
                half_gain: [1834, 0, 0, 0, 0, 2319, 0, 0, 0, 0, 14457, 0, 0, 0, 0, 839] # calibrate by using half of the sigma in us, then recalibrate the gain
                half_gain_pi_sigma: [927, 0, 0, 0, 0, 1315, 0, 0, 0, 0, 7212, 0, 0, 0, 0, 460] # calibrate using same sigma, recalibrate the gain
                type: 'gauss'
            pi_ef:
                sigma: [0.02, 0.02, 0.02, 0.02, 0.025, 0.025, 0.025, 0.025, 0.015, 0.015, 0.015, 0.015, 0.02, 0.02, 0.02, 0.02] # [us]
                gain: [1346, 0, 0, 0, 0, 1951, 0, 0, 0, 10044, 10074, 0, 0, 719, 0, 717]
                half_gain: [1346, 0, 0, 0, 0, 1951, 0, 0, 0, 0, 9979, 0, 0, 0, 0, 714] # calibrate by using half of the sigma in us, then recalibrate the gain
                half_gain_pi_sigma: [673, 0, 0, 0, 0, 975, 0, 0, 0, 0, 5049, 0, 0, 0, 0, 337] # calibrate by using half of the sigma in us, then recalibrate the gain
                type: 'gauss'
            pi_EgGf: # drive on Q1 to perform a swap with Qx
                gain: [32000, 0, 30000, 16000]
                sigma: [0.586, 0, 0.8, 0.44643] # [us], assume 3 clock cycle * 4 sigma ramp, this is the "total length" for a flat top pulse
                type: 'flat_top'
            pi_EgGf_Q: # drive on Qx to perform a swap with Q1. For Q2: set Q0 in g before starting. For Q3: set Q0 in e before starting
                gain: [0, 0, 21000, 14400]
                sigma: [0, 0, 0.410, 0.326] # [us], assume 3 clock cycle * 4 sigma ramp, this is the "total length" for a flat top pulse
                phase: [0, 0, 8.8, 24.0] # in degrees, this should be the 2x the phase that shows up in the tomo
                half_sigma: [0, 0, 0.212, 0.172]
                half_phase: [0, 0, 15.0, 21.0]
                type: 'flat_top'
            pi_f0g1: # drive on Qx to do an f0-g1 with Qx resonator
                gain: [32000, 32000, 32000, 32000]
                sigma: [0.536, 0.585, 1.540, 1.040] # [us], assume 3 clock cycle * 4 sigma ramp, this is the "total length" for a flat top pulse
                idle: [3, 6, 12, 8]
                type: 'flat_top'

            pulse_pp:
                gain: [3250, 4875, 0, 0]
                filename: '240722_qram_4q_2qubit_++gg'
            pulse_1p:
                gain: [4100, 5100, 0, 0]
                filename: '240722_qram_4q_2qubit_e+gg'
            pulse_p1:
                gain: [2800, 7000, 0, 0]
                filename: '240722_qram_4q_2qubit_+egg'

            # pi_ge_crosstalk: # pulse to apply on Qx to cancel drive crosstalk during simultaneous pi_EgGf_Q pulses on Q2, Q3
            #     delta: [0, 50, 0, 0] # f_crosstalk - f_ge
            #     gain: [0, 100, 0, 0] 
            #     phase: [0, 0, 0, 0]
            #     type: 'flat_top'
            # pi_ge_adiabatic:
            #     gain: [-1, 25000, -1, -1]
            #     mu: [0, 6, 0, 0]
            #     beta: [0, 4, 0, 0]
            #     period: [0, 0.480, 0, 0]
            # pi_ge_IQ:
            #     gain: 1373
            pi_ge_slow:
                gain: [-1, 100, -1, -1]
                sigma: [-1, 0.250, -1, -1] # [us]
                # half_gain: [None, None, None, None] # calibrate by using half of the sigma in us, then recalibrate the gain
                type: 'gauss'
            pi_Q1_ZZ_slow: # SLOW pi pulse length for Q1 when other qubits are in e
                gain: [100, 0, -1, -1]
                sigma: [0.250, 0, -1, -1] # [us]
                type: 'gauss'

hw:
    soc:
        dacs:
        # dac types: full (full gen - all gens in standard firmware) or int4, mux4 (q3diamond)
        # For mux4, all 4 readouts are on the same DAC (ch 6). Need to make sure none of the
        # 4 muxed readout freqs are not in the same bin, which are fs/16 wide
            qubit:
                ch: [0, 1, 2, 3]
                type: 'full'
                nyquist: [2, 1, 2, 2]
                mixer_freq: [0, 0, 0, 0]
            swap:
                ch: 1
                type: 'full'
                nyquist: 1
                mixer_freq: 0
            swap_f0g1:
                ch: [1, 1, 5, 5]
                type: ['full', 'full', 'full', 'full']
                nyquist: 1
                mixer_freq: 0
            swap_Q:
                ch: [0, -1, 2, 3]
                type: ['full', None, 'full', 'full']
                nyquist: [2, 0, 2, 2]
                mixer_freq: 0
            readout:
                ch: [6, 4, 6, 6]
                type: ['mux4', 'full', 'mux4', 'mux4']
                mixer_freq: [7200, 0, 7200, 7200] # [MHz] freq to mix up
                nyquist: [2, 2, 2, 2]
            res_pump:
                ch: 4
                type: 'full'
                mixer_freq: 0 # [MHz] freq to mix up
                nyquist: 2
            delay_chs:
                ch: [0, 1, 2, 3, 4, 5, 6]
                # delay_ns: [8.7, 8.5, 0, 7.6, 24, 20, 74.5]
                delay_ns: [8.7, 8.5, 0, 7.6, 24, 20, 104.5]
        adcs:
            readout:
                ch: [0, 1, 2, 3]
    lo:
        twpa:
            # opt for all
            # frequency: 8250.0e6
            # power: -1.6 # min -40, max +15 dBm
            # opt for q2, q3
            frequency: 8170.0e6
            power: -1.0 # min -40, max +15 dBm
        readout:
            frequency: 0
            power: 0 # mixer wants 7 dBm

aliases: # for use in instrument manager
    readout_LO: SC_20A1
    twpa_LO: SC_26C1
    soc: Qick187 # 10.108.30.52
    # soc: Qick60 # 10.108.30.60 BF1
    # soc: Qick233 # SLAC BF5 QRAM