device:
    qubit:
        T1: [50, 100, 29, 100] # [us]
        f_ge: [828.193, 3470.7039558072906, 160.544663455941, 445.697747526901] # [MHz]
        f_ef: [637.4704365863639, 3370.260942584849, -81.47654241457579, 274.4176421308761] # [MHz]
        f_EgGf: [2007.267, -1, 2682, 2385.8] # [MHz] expect to be ge_1 + ef_1 - ge_0
        gs: [43, 0, 54, 40] # [MHz] from theoretical comparison for ZZ shift
        pulses:
            pi_ge:
                gain: [30000, 30000, 30000, 30000]
                sigma: [0.135, 0.0882, 0.198, 0.135] # [us]
                type: [gauss, gauss, gauss, gauss]
            pi_ef:
                gain: [25271, 22889, 30000, 19229]
                sigma: [0.090, 0.095, 0.095, 0.090] # [us]
                type: gauss
            pi_EgGf:
                gain: [2500, 0, 3000, 3000]
                sigma: [0.335, 0, 0.400, 0.400] # [us]
                type: const
    
    readout:
        trig_offset: 125 # [Clock ticks]
        # frequency: [810.409984606071, -804.7555447534925, -82.3, 79.3372763161615] # [MHz] max: 860 MHz, must be in separate bins = fs/16 (hi/lo power: 7.681/7.686, 5.775/5.781, 6.787/6.793, 6.949/6.955)
        frequency: [812.37, -806.77, -80.4, 79.63708892384405] # [MHz] max: 860 MHz, must be in separate bins = fs/16 (hi/lo power: 7.681/7.686, 5.775/5.781, 6.787/6.793, 6.949/6.955)
        lo_sideband: [1, -1, 1, 1] # whether taking the +/- sideband after LO
        gain: [0.300, 0.270, 0.270, 0.200] # [MUX units: range -1 to 1, signed amplitude]
        # phase: [0, 0, 90, 0] # degrees 
        # threshold_ge: [0, -73, 0.75, 0] # adc units
        # threshold_ef: [1, 1, 1, 1] # adc units
        readout_length: [10, 10, 10, 10] # [us]
        relax_delay: [150, 300, 140, 150] # [us]
    
hw:
    soc:
        dacs:
        # dac types: full (full gen - all gens in standard firmware) or int4, mux4 (q3diamond)
        # For mux4, all 4 readouts are on the same DAC (ch 6). Need to make sure none of the
        # 4 muxed readout freqs are not in the same bin, which are fs/16 wide
            qubit:
                ch: [0, 5, 0, 0]
                # ch: [0, 4, 0, 0]
                type: ['int4', 'full', 'int4', 'int4']
                mixer_freq: [4000, 0, 4000, 4000]
                nyquist: [2, 2, 2, 2]
            swap:
                ch: [4, -1, 4, 4]
                type: ['full', None, 'full', 'full']
                # nyquist: [2, 0, 2, 2]
                nyquist: [1, 0, 1, 1]
            readout:
                # ch: 1
                # type: 'full'
                # nyquist: 1
                # ch: 0
                # type: 'int4'
                # mixer_freq: 2000 # [MHz] freq to mix up
                # nyquist: 1
                ch: 6
                type: 'mux4'
                mixer_freq: 950 # [MHz] freq to mix up
                nyquist: 1
        adcs:
            readout:
                ch: [0, 1, 2, 3]
    lo:
        readout:
            frequency: 5925e6
            power: 7 # mixer wants 7 dBm
            
aliases: # for use in instrument manager
    readout_LO: SC_26C1
    soc: Qick187